import type { Hotspot, ConflictZone, MilitaryBase, UnderseaCable, NuclearFacility, StrategicWaterway, APTGroup } from '@/types';

// Hotspot levels are NOT hardcoded - they are dynamically calculated based on news activity
// All hotspots start at 'low' and rise to 'elevated' or 'high' based on matching news items
export const INTEL_HOTSPOTS: Hotspot[] = [
  {
    id: 'dc',
    name: 'DC',
    subtext: 'Pentagon Pizza Index',
    lat: 38.9,
    lon: -77.0,
    keywords: ['pentagon', 'white house', 'congress', 'cia', 'nsa', 'washington', 'biden', 'trump', 'house', 'senate', 'supreme court', 'vance', 'elon', 'us '],
    agencies: ['Pentagon', 'CIA', 'NSA', 'State Dept'],
    description: 'US government and military headquarters. Intelligence community center.',
    status: 'Monitoring',
  },
  {
    id: 'moscow',
    name: 'Moscow',
    subtext: 'Kremlin Activity',
    lat: 55.75,
    lon: 37.6,
    keywords: ['kremlin', 'putin', 'russia', 'fsb', 'moscow', 'russian'],
    agencies: ['Kremlin', 'FSB', 'GRU', 'SVR'],
    description: 'Russian Federation command center. Military operations hub.',
    status: 'Monitoring',
  },
  {
    id: 'beijing',
    name: 'Beijing',
    subtext: 'PLA/MSS Activity',
    lat: 39.9,
    lon: 116.4,
    keywords: ['beijing', 'xi', 'china', 'pla', 'ccp', 'chinese', 'jinping'],
    agencies: ['PLA', 'MSS', 'CCP Politburo'],
    description: 'Chinese Communist Party headquarters. PLA command center.',
    status: 'Monitoring',
  },
  {
    id: 'kyiv',
    name: 'Kyiv',
    subtext: 'Conflict Zone',
    lat: 50.45,
    lon: 30.5,
    keywords: ['kyiv', 'ukraine', 'zelensky', 'ukrainian', 'kiev'],
    agencies: ['Ukrainian Armed Forces', 'SBU'],
    description: 'Active conflict zone. NATO support operations.',
    status: 'Monitoring',
  },
  {
    id: 'taipei',
    name: 'Taipei',
    subtext: 'Strait Watch',
    lat: 25.03,
    lon: 121.5,
    keywords: ['taiwan', 'taipei', 'tsmc', 'strait', 'taiwanese'],
    agencies: ['ROC Military', 'TSMC'],
    description: 'Taiwan Strait tensions. Semiconductor supply chain.',
    status: 'Monitoring',
  },
  {
    id: 'tehran',
    name: 'Tehran',
    subtext: 'IRGC Activity',
    lat: 35.7,
    lon: 51.4,
    keywords: ['iran', 'tehran', 'irgc', 'khamenei', 'persian', 'iranian'],
    agencies: ['IRGC', 'Quds Force', 'MOIS'],
    description: 'Iranian nuclear program. Regional proxy operations.',
    status: 'Monitoring',
  },
  {
    id: 'telaviv',
    name: 'Tel Aviv',
    subtext: 'Mossad/IDF',
    lat: 32.1,
    lon: 34.8,
    keywords: ['israel', 'idf', 'mossad', 'gaza', 'netanyahu', 'israeli', 'hamas', 'hezbollah'],
    agencies: ['IDF', 'Mossad', 'Shin Bet'],
    description: 'Military operations. Regional security. Intelligence activities.',
    status: 'Monitoring',
  },
  {
    id: 'pyongyang',
    name: 'Pyongyang',
    subtext: 'DPRK Watch',
    lat: 39.0,
    lon: 125.75,
    keywords: ['north korea', 'kim', 'pyongyang', 'dprk', 'korean'],
    agencies: ['KPA', 'RGB', 'Lazarus Group'],
    description: 'Nuclear weapons program. Missile testing. Cyber operations.',
    status: 'Monitoring',
  },
  {
    id: 'london',
    name: 'London',
    subtext: 'GCHQ/MI6',
    lat: 51.5,
    lon: -0.12,
    keywords: ['london', 'uk', 'britain', 'gchq', 'mi6', 'british'],
    agencies: ['MI6', 'GCHQ', 'MI5'],
    description: 'UK intelligence headquarters. Five Eyes member.',
    status: 'Monitoring',
  },
  {
    id: 'brussels',
    name: 'Brussels',
    subtext: 'NATO HQ',
    lat: 50.85,
    lon: 4.35,
    keywords: ['nato', 'brussels', 'eu', 'european union', 'europe'],
    agencies: ['NATO', 'EU Commission'],
    description: 'NATO alliance headquarters. European Union center.',
    status: 'Monitoring',
  },
  {
    id: 'caracas',
    name: 'Caracas',
    subtext: 'Venezuela Crisis',
    lat: 10.5,
    lon: -66.9,
    keywords: ['venezuela', 'maduro', 'caracas', 'venezuelan'],
    agencies: ['Maduro Govt', 'SEBIN'],
    description: 'Political crisis. Economic sanctions. Regional instability.',
    status: 'Monitoring',
  },
  {
    id: 'nuuk',
    name: 'Nuuk',
    subtext: 'Arctic Dispute',
    lat: 64.18,
    lon: -51.7,
    keywords: ['greenland', 'nuuk', 'arctic', 'denmark', 'danish'],
    agencies: ['Danish Defence', 'US Space Force', 'Arctic Council'],
    description: 'Arctic strategic territory. US military presence, sovereignty questions.',
    status: 'Monitoring',
  },
  // Middle East hotspots
  {
    id: 'riyadh',
    name: 'Riyadh',
    subtext: 'Saudi GIP/MBS',
    lat: 24.7,
    lon: 46.7,
    keywords: ['saudi', 'riyadh', 'mbs', 'aramco', 'opec', 'saudi arabia'],
    agencies: ['GIP', 'Saudi Royal Court', 'Aramco'],
    description: 'Saudi Arabia power center. OPEC+ decisions. Regional influence.',
    status: 'Monitoring',
  },
  {
    id: 'cairo',
    name: 'Cairo',
    subtext: 'Egypt/GIS',
    lat: 30.0,
    lon: 31.2,
    keywords: ['egypt', 'cairo', 'sisi', 'egyptian', 'suez'],
    agencies: ['GIS', 'Egyptian Armed Forces'],
    description: 'Egyptian command. Gaza border control. Suez Canal security.',
    status: 'Monitoring',
  },
  {
    id: 'baghdad',
    name: 'Baghdad',
    subtext: 'Iraq/PMF',
    lat: 33.3,
    lon: 44.4,
    keywords: ['iraq', 'baghdad', 'iraqi', 'pmf', 'militia'],
    agencies: ['Iraqi Security Forces', 'PMF', 'US Embassy'],
    description: 'Iraqi government. Iran-backed militias. US military presence.',
    status: 'Monitoring',
  },
  {
    id: 'damascus',
    name: 'Damascus',
    subtext: 'Syria Crisis',
    lat: 33.5,
    lon: 36.3,
    keywords: ['syria', 'damascus', 'assad', 'syrian', 'hts'],
    agencies: ['Syrian Govt', 'HTS', 'Russian Forces', 'Turkish Forces'],
    description: 'Syrian civil war aftermath. Multiple foreign interventions.',
    status: 'Monitoring',
  },
  {
    id: 'doha',
    name: 'Doha',
    subtext: 'Qatar/Al Udeid',
    lat: 25.3,
    lon: 51.5,
    keywords: ['qatar', 'doha', 'qatari', 'al jazeera'],
    agencies: ['Qatari State Security', 'CENTCOM Forward HQ'],
    description: 'Qatar diplomatic hub. US CENTCOM base. Al Jazeera HQ.',
    status: 'Monitoring',
  },
  {
    id: 'ankara',
    name: 'Ankara',
    subtext: 'Turkey/MIT',
    lat: 39.9,
    lon: 32.9,
    keywords: ['turkey', 'ankara', 'erdogan', 'turkish', 'mit'],
    agencies: ['MIT', 'Turkish Armed Forces', 'AKP'],
    description: 'NATO member. Kurdish conflict. Syria/Libya operations.',
    status: 'Monitoring',
  },
  {
    id: 'beirut',
    name: 'Beirut',
    subtext: 'Lebanon/Hezbollah',
    lat: 33.9,
    lon: 35.5,
    keywords: ['lebanon', 'beirut', 'hezbollah', 'lebanese', 'nasrallah'],
    agencies: ['LAF', 'Hezbollah', 'UNIFIL'],
    description: 'Lebanon crisis. Hezbollah stronghold. Israel border tensions.',
    status: 'Monitoring',
  },
  {
    id: 'sanaa',
    name: "Sana'a",
    subtext: 'Yemen/Houthis',
    lat: 15.4,
    lon: 44.2,
    keywords: ['yemen', 'houthi', 'sanaa', 'yemeni', 'red sea'],
    agencies: ['Houthi Forces', 'Saudi Coalition', 'US Navy'],
    description: 'Yemen conflict. Houthi Red Sea attacks. Shipping disruption.',
    status: 'Monitoring',
  },
  {
    id: 'abudhabi',
    name: 'Abu Dhabi',
    subtext: 'UAE/ECSR',
    lat: 24.5,
    lon: 54.4,
    keywords: ['uae', 'abu dhabi', 'emirates', 'emirati', 'dubai'],
    agencies: ['ECSR', 'UAE Armed Forces'],
    description: 'UAE strategic hub. Regional military operations.',
    status: 'Monitoring',
  },
];

export const STRATEGIC_WATERWAYS: StrategicWaterway[] = [
  { id: 'taiwan_strait', name: 'TAIWAN STRAIT', lat: 24.0, lon: 119.5, description: 'Critical shipping lane, PLA activity' },
  { id: 'malacca_strait', name: 'MALACCA STRAIT', lat: 2.5, lon: 101.5, description: 'Major oil shipping route' },
  { id: 'hormuz_strait', name: 'STRAIT OF HORMUZ', lat: 26.5, lon: 56.5, description: 'Oil chokepoint, Iran control' },
  { id: 'bosphorus', name: 'BOSPHORUS STRAIT', lat: 41.1, lon: 29.0, description: 'Black Sea access, Turkey control' },
  { id: 'suez', name: 'SUEZ CANAL', lat: 30.5, lon: 32.3, description: 'Europe-Asia shipping' },
  { id: 'panama', name: 'PANAMA CANAL', lat: 9.1, lon: -79.7, description: 'Americas shipping route' },
];

export const APT_GROUPS: APTGroup[] = [
  { id: 'apt28', name: 'APT28/29', aka: 'Fancy Bear/Cozy Bear', sponsor: 'Russia (GRU/FSB)', lat: 55.0, lon: 40.0 },
  { id: 'apt41', name: 'APT41', aka: 'Double Dragon', sponsor: 'China (MSS)', lat: 38.0, lon: 118.0 },
  { id: 'lazarus', name: 'Lazarus', aka: 'Hidden Cobra', sponsor: 'North Korea (RGB)', lat: 38.5, lon: 127.0 },
  { id: 'apt33', name: 'APT33/35', aka: 'Elfin/Charming Kitten', sponsor: 'Iran (IRGC)', lat: 34.0, lon: 53.0 },
];

export const CONFLICT_ZONES: ConflictZone[] = [
  {
    id: 'ukraine',
    name: 'Ukraine Conflict',
    coords: [[30, 52], [40, 52], [40, 44], [30, 44]],
    center: [35, 48],
    intensity: 'high',
    parties: ['Russia', 'Ukraine', 'NATO (support)'],
    casualties: '500,000+ (est.)',
    displaced: '6.5M+ refugees',
    keywords: ['ukraine', 'russia', 'zelensky', 'putin', 'donbas', 'crimea'],
    startDate: 'Feb 24, 2022',
    location: '48.0°N, 37.5°E',
    description: 'Full-scale Russian invasion of Ukraine. Active frontlines in Donetsk, Luhansk, Zaporizhzhia, and Kherson oblasts. Heavy artillery, drone warfare, and trench combat.',
    keyDevelopments: ['Battle of Bakhmut', 'Kursk incursion', 'Black Sea drone strikes', 'Infrastructure attacks'],
  },
  {
    id: 'gaza',
    name: 'Gaza Conflict',
    coords: [[34, 32], [35, 32], [35, 31], [34, 31]],
    center: [34.5, 31.5],
    intensity: 'high',
    parties: ['Israel', 'Hamas', 'Hezbollah', 'PIJ'],
    casualties: '40,000+ (Gaza)',
    displaced: '2M+ displaced',
    keywords: ['gaza', 'israel', 'hamas', 'palestinian'],
    startDate: 'Oct 7, 2023',
    location: '31.5°N, 34.5°E',
    description: 'Israeli military operations in Gaza following October 7 attacks. Ground invasion, aerial bombardment. Humanitarian crisis. Regional escalation with Hezbollah.',
    keyDevelopments: ['Rafah ground operation', 'Humanitarian crisis', 'Hostage negotiations', 'Iran-backed attacks'],
  },
  {
    id: 'sudan',
    name: 'Sudan Civil War',
    coords: [[22, 22], [38, 22], [38, 8], [22, 8]],
    center: [30, 15],
    intensity: 'high',
    parties: ['Sudanese Armed Forces (SAF)', 'Rapid Support Forces (RSF)'],
    casualties: '15,000+ killed',
    displaced: '10M+ displaced',
    keywords: ['sudan', 'khartoum', 'darfur'],
    startDate: 'Apr 15, 2023',
    location: '15.0°N, 32.5°E',
    description: 'Power struggle between SAF and RSF paramilitary. Fighting centered around Khartoum, Darfur. Major humanitarian catastrophe with famine conditions.',
    keyDevelopments: ['Khartoum battle', 'Darfur massacres', 'El Fasher siege', 'Famine declared'],
  },
  {
    id: 'myanmar',
    name: 'Myanmar Civil War',
    coords: [[92, 28], [101, 28], [101, 10], [92, 10]],
    center: [96, 19],
    intensity: 'medium',
    parties: ['Military junta', 'NUG', 'Ethnic armed groups'],
    casualties: '50,000+ (est.)',
    displaced: '2.6M+ displaced',
    keywords: ['myanmar', 'burma', 'rohingya'],
    startDate: 'Feb 1, 2021',
    location: '19.0°N, 96.0°E',
    description: 'Civil war following military coup. Resistance forces gaining ground. Multiple ethnic armed organizations. Humanitarian crisis.',
    keyDevelopments: ['Operation 1027', 'Junta airstrikes', 'Border clashes', 'Resistance advances'],
  },
];

export const MILITARY_BASES: MilitaryBase[] = [
  // US/NATO
  { id: 'ramstein', name: 'Ramstein AB', lat: 49.44, lon: 7.6, type: 'us-nato' },
  { id: 'diego_garcia', name: 'Diego Garcia', lat: -7.32, lon: 72.42, type: 'us-nato' },
  { id: 'okinawa', name: 'Okinawa', lat: 26.5, lon: 127.9, type: 'us-nato' },
  { id: 'guam', name: 'Guam', lat: 13.45, lon: 144.8, type: 'us-nato' },
  { id: 'qatar', name: 'Al Udeid AB', lat: 25.12, lon: 51.32, type: 'us-nato' },
  { id: 'djibouti_us', name: 'Camp Lemonnier', lat: 11.55, lon: 43.15, type: 'us-nato' },
  { id: 'bahrain', name: 'NSA Bahrain', lat: 26.23, lon: 50.58, type: 'us-nato' },
  { id: 'yokosuka', name: 'Yokosuka', lat: 35.28, lon: 139.67, type: 'us-nato' },
  { id: 'rota', name: 'Naval Rota', lat: 36.62, lon: -6.35, type: 'us-nato' },
  { id: 'incirlik', name: 'Incirlik AB', lat: 37.0, lon: 35.43, type: 'us-nato' },
  // China
  { id: 'djibouti_cn', name: 'PLA Djibouti', lat: 11.59, lon: 43.05, type: 'china' },
  { id: 'woody_island', name: 'Woody Island', lat: 16.83, lon: 112.33, type: 'china' },
  { id: 'fiery_cross', name: 'Fiery Cross', lat: 9.55, lon: 112.89, type: 'china' },
  { id: 'mischief_reef', name: 'Mischief Reef', lat: 9.9, lon: 115.53, type: 'china' },
  { id: 'subi_reef', name: 'Subi Reef', lat: 10.92, lon: 114.08, type: 'china' },
  // Russia
  { id: 'kaliningrad', name: 'Kaliningrad', lat: 54.71, lon: 20.51, type: 'russia' },
  { id: 'tartus', name: 'Tartus (Syria)', lat: 34.89, lon: 35.87, type: 'russia' },
  { id: 'sevastopol', name: 'Sevastopol', lat: 44.6, lon: 33.5, type: 'russia' },
  { id: 'vladivostok', name: 'Vladivostok', lat: 43.12, lon: 131.9, type: 'russia' },
  { id: 'murmansk', name: 'Murmansk', lat: 68.97, lon: 33.09, type: 'russia' },
];

export const UNDERSEA_CABLES: UnderseaCable[] = [
  {
    id: 'transatlantic_1',
    name: 'TAT-14',
    points: [[-74.0, 40.7], [-30.0, 45.0], [-9.0, 52.0]],
    major: true,
  },
  {
    id: 'transpacific_1',
    name: 'Unity',
    points: [[-122.4, 37.8], [-155.0, 25.0], [139.7, 35.7]],
    major: true,
  },
  {
    id: 'seamewe5',
    name: 'SEA-ME-WE 5',
    points: [[103.8, 1.3], [73.0, 15.0], [43.0, 12.0], [32.5, 30.0], [12.5, 42.0]],
    major: true,
  },
  {
    id: 'aae1',
    name: 'AAE-1',
    points: [[103.8, 1.3], [80.0, 6.0], [55.0, 15.0], [43.0, 12.0], [36.0, 32.0]],
    major: true,
  },
  {
    id: 'curie',
    name: 'Curie',
    points: [[-122.4, 37.8], [-90.0, 10.0], [-77.0, -12.0]],
    major: true,
  },
  {
    id: 'marea',
    name: 'MAREA',
    points: [[-73.0, 39.0], [-30.0, 42.0], [-9.0, 37.0]],
    major: true,
  },
];

export const NUCLEAR_FACILITIES: NuclearFacility[] = [
  { id: 'zaporizhzhia', name: 'Zaporizhzhia NPP', lat: 47.51, lon: 34.58, type: 'plant', status: 'contested' },
  { id: 'natanz', name: 'Natanz', lat: 33.72, lon: 51.73, type: 'enrichment', status: 'active' },
  { id: 'fordow', name: 'Fordow', lat: 34.88, lon: 51.0, type: 'enrichment', status: 'active' },
  { id: 'yongbyon', name: 'Yongbyon', lat: 39.8, lon: 125.75, type: 'weapons', status: 'active' },
  { id: 'dimona', name: 'Dimona', lat: 31.0, lon: 35.15, type: 'weapons', status: 'active' },
];

export const SANCTIONED_COUNTRIES: Record<number, 'severe' | 'high' | 'moderate'> = {
  408: 'severe',   // North Korea
  728: 'severe',   // South Sudan
  760: 'severe',   // Syria
  364: 'high',     // Iran
  643: 'high',     // Russia
  112: 'high',     // Belarus
  862: 'moderate', // Venezuela
  104: 'moderate', // Myanmar
  178: 'moderate', // Congo
};

export const MAP_URLS = {
  world: 'https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json',
  us: 'https://cdn.jsdelivr.net/npm/us-atlas@3/states-10m.json',
};
